spring:
  datasource:
    # rewriteBatchedStatements=true ???????
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root.123
    driver-class-name: com.mysql.cj.jdbc.Driver